# Generated by Django 2.2.4 on 2019-08-24 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('intended_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('logo_url', models.URLField()),
                ('meta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.Meta', verbose_name='Meta')),
            ],
        ),
    ]
